channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=22.1.1
- pip:
  - mlflow
  - cffi==1.15.0
  - fsspec==2022.5.0
  - pillow==9.1.1
  - pydot==1.4.2
  - scikit-learn==1.1.1
  - tensorflow-macos==2.9.0
name: mlflow-env
